language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# Commands you want to run that will verify your build.
script: phpunit

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always